ci:
    skip: [mypy-local]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.8.5'
    hooks:
    -   id: ruff
        name: linting code with Ruff
        args: [ "--fix" ]
    -   id: ruff-format
        name: format code using Ruff formatter
-   repo: local
    hooks:
    -   id: mypy-local
        name: type check with mypy locally
        entry: mypy
        language: system
        types: [ python ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'
    hooks:
    -   id: mypy
        name: type check with mypy mirror to run on CI
