[project]
name = "car"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mypy>=1.14.1",
    "pre-commit>=4.0.1",
    "ruff>=0.8.5",
    "selenium>=4.27.1",
    "webdriver-manager>=4.0.2",
]
